/* AUTO-GENERATED by scripts/port-content.mjs — do not edit by hand.
 * Prose ported verbatim from `main:faq.html`. English only, as it was
 * there: this page carried no data-i18n attributes. Presentation classes were dropped;
 * the prose stylesheet styles by element.
 */
import styles from './prose.module.css';

export function FaqContent() {
  return (
    <div className={styles.prose}>
      <h1>Frequently Asked Questions</h1>
      <p>Everything you need to know about CyprusWay</p>
      <h2>How does booking work on CyprusWay?</h2>
      <p>CyprusWay helps you find and compare hotels, rental cars, activities, and airport transfers. When you're ready to book, the app connects you to trusted third-party travel providers where you complete your reservation. CyprusWay does not process payments or hold bookings — the provider handles everything. CyprusWay may earn a commission from bookings made through these links, at no extra cost to you.</p>
      <h2>Which booking providers do you use?</h2>
      <p>CyprusWay connects users to reputable travel providers for different categories: accommodation providers for hotels and villas, activity platforms for tours and excursions, car rental services, and airport transfer operators. The specific providers available may vary. CyprusWay is not a partner, representative, or agent of any named provider — we direct users to third-party booking platforms where they complete their own reservation.</p>
      <h2>What if I need to cancel or change a booking?</h2>
      <p>All bookings are made directly with the third-party provider. Cancellation policies, changes, refunds, and customer service are handled entirely by that provider. CyprusWay does not manage reservations and cannot cancel or modify bookings on your behalf. Please refer to the confirmation email from the provider for their cancellation terms and contact information.</p>
      <h2>Is CyprusWay free to use?</h2>
      <p>Yes. The core CyprusWay experience — browsing curated places, using the manual itinerary builder, exploring a selection of virtual tours, and asking Pete a limited number of questions per day — is completely free. For the full experience, including all 25 virtual tours, AI-powered trip planning, unlimited Pete access, itinerary regeneration, and PDF export, you can unlock CyprusWay Premium for a one-time payment of €4.99. No subscription, no recurring charges.</p>
      <h2>Which languages are supported?</h2>
      <p>CyprusWay is available in five languages: English, Polish, German, Greek, and Swedish. You can switch languages at any time using the language selector in the top navigation bar. The app and all place content are fully translated across these languages. More languages may be added in the future based on demand.</p>
      <h2>What does CyprusWay Premium unlock?</h2>
      <p>CyprusWay Premium (€4.99 one-time) unlocks: all 25 immersive 360° virtual tours, the AI Trip Planner that builds personalised day-by-day itineraries, unlimited questions for Ask Pete (your Cyprus travel companion), the ability to regenerate individual days in your itinerary, and PDF export of your finished trip plan. Premium access works across all platforms — website, iOS, and Android — as long as you sign in with the same account.</p>
      <h2>How do I use the CyprusWay app?</h2>
      <p>CyprusWay is a mobile travel app. You start by exploring curated places across Cyprus or planning a trip. The app helps you discover beaches, archaeological sites, monasteries, nature trails, villages, and more — each with photos, descriptions, opening hours, and practical tips. You can preview places in 360° virtual tours, build a day-by-day itinerary manually or with AI assistance, ask Pete travel questions, and arrange your bookings through trusted providers. The app is your single companion for planning and experiencing Cyprus.</p>
      <h2>Where does CyprusWay cover?</h2>
      <p>CyprusWay covers curated places across the entire island of Cyprus — from the beaches of Ayia Napa and Protaras on the eastern coast, to the archaeological treasures of Paphos and Limassol on the south and west coasts, the city of Larnaca with its salt lake and promenade, and the Troodos Mountains in the centre. We cover beaches, historical sites, monasteries and churches, nature trails, traditional villages, wineries, and more. See our <a href="destinations.html">Destinations page</a> for full details.</p>
      <h2>Who operates CyprusWay?</h2>
      <p>CyprusWay is operated by Almisource LTD, a company focused on building practical, content-rich travel tools for specific destinations. We are not a global booking platform — we are a focused Cyprus travel companion. You can reach us at <a href="mailto:partners@cyprusway.eu">partners@cyprusway.eu</a>.</p>
    </div>
  );
}
