/* AUTO-GENERATED by scripts/port-content.mjs — do not edit by hand.
 * Prose ported verbatim from `main:privacy.html`. English only, as it was
 * there: this page carried no data-i18n attributes. Presentation classes were dropped;
 * the prose stylesheet styles by element.
 */
import styles from './prose.module.css';

export function PrivacyContent() {
  return (
    <div className={styles.prose}>
      <h1>Privacy Policy</h1>
      <p>Last updated: May 2026</p>
      <h2>1. Who we are</h2>
      <p>CyprusWay is a mobile travel app and marketing website operated by <strong>Almisource LTD</strong>. This privacy policy explains how we collect, use, and protect your information when you visit this website or use the CyprusWay mobile application.</p>
      <h2>2. What information we collect</h2>
      <p>When you visit this website, we may collect:</p>
      <ul>
      <li><strong>Usage data:</strong> Basic, anonymous information about how you interact with the site — pages visited, time spent, and browser type. This data does not identify you personally.</li>
      <li><strong>Contact information:</strong> If you email us at partners@cyprusway.eu, we receive your email address and any information you choose to include in your message.</li>
      </ul>
      <p>The CyprusWay mobile application may collect additional information, including account details if you create one, travel preferences you set, and booking-related data. The app's own privacy notice, accessible within the application, covers those data practices in full.</p>
      <h2>3. Cookies</h2>
      <p>This website uses cookies — small text files placed on your device — for essential functionality and to understand how the site is used. We use a minimal set of cookies and do not deploy advertising or third-party tracking cookies on this marketing website.</p>
      <p>Our <strong>mobile application</strong> uses <strong>affiliate links and affiliate tracking cookies</strong>. When you click through to a third-party booking provider (such as a hotel, car rental, or activity provider) from the CyprusWay app, a tracking cookie may be placed on your device by that provider. This cookie enables the provider to record that CyprusWay referred you. If you complete a booking, CyprusWay may earn a commission at no extra cost to you. These cookies are set and managed by the third-party provider, not by us, and are subject to that provider's own privacy policy.</p>
      <h2>4. Affiliate links and commissions</h2>
      <p>CyprusWay may earn a commission when you make a booking through links to third-party travel providers featured in our app. These commissions do not affect the price you pay. The providers are responsible for handling your booking, payment, and any related customer service. CyprusWay does not process payments or hold your payment information.</p>
      <h2>5. How we use your information</h2>
      <p>We use the information we collect to:</p>
      <ul>
      <li>Operate and improve the website and the CyprusWay app</li>
      <li>Respond to your enquiries sent to partners@cyprusway.eu</li>
      <li>Understand how visitors and users interact with our service so we can make it better</li>
      </ul>
      <p>We do <strong>not</strong> sell your personal information to third parties. We do not share your personal information with third parties except as necessary to operate our service (for example, with a hosting provider) or as required by law.</p>
      <h2>6. Data retention</h2>
      <p>We retain your information only for as long as necessary to fulfil the purposes described in this policy. Email correspondence is kept for a reasonable period to maintain a record of communication. Usage data is retained in aggregate, anonymous form.</p>
      <p>For users of the CyprusWay mobile application who create an account, the app retains conversation history with the Ask Pete feature for 90 days, in compliance with EU data protection regulations. Account-related data is deleted when you delete your account.</p>
      <h2>7. Your rights</h2>
      <p>Depending on where you are located, you may have rights regarding your personal information, including the right to access, correct, or delete your data. Cyprus is in the European Union, and CyprusWay complies with the General Data Protection Regulation (GDPR). To exercise any of your rights, contact us at <a href="mailto:partners@cyprusway.eu">partners@cyprusway.eu</a>.</p>
      <h2>8. Third-party services</h2>
      <p>This website may contain links to third-party websites and services, including booking providers. We are not responsible for the privacy practices of those third parties. We encourage you to read the privacy policies of any website you visit through a link from our site or app.</p>
      <h2>9. Changes to this policy</h2>
      <p>We may update this privacy policy from time to time. When we do, we will revise the "Last updated" date at the top of this page. We encourage you to review this policy periodically.</p>
      <h2>10. Contact</h2>
      <p>If you have questions about this privacy policy or how your data is handled, contact us at:</p>
      <p><strong>Email:</strong> <a href="mailto:partners@cyprusway.eu">partners@cyprusway.eu</a><br />
      <strong>Company:</strong> Almisource LTD</p>
    </div>
  );
}
