/**
 * Port the prose of the legal and FAQ pages into TSX components.
 *
 * These three pages carry no `data-i18n` attributes — they are English-only today, so
 * porting them as English is parity, not a regression. (`about.html` IS translated,
 * 37 keys, and is hand-built against the dictionary instead; it is not in this list.)
 *
 * Mechanical rather than retyped: legal text is exactly the wrong thing to transcribe
 * by hand. Read from git so this stays runnable after the vanilla files are deleted.
 *
 *   node scripts/port-content.mjs
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'src/routes/content');
const SOURCE_REF = 'main';

const PAGES = [
  { file: 'privacy.html', component: 'PrivacyContent', out: 'PrivacyContent.tsx' },
  { file: 'terms.html', component: 'TermsContent', out: 'TermsContent.tsx' },
  { file: 'faq.html', component: 'FaqContent', out: 'FaqContent.tsx' },
];

const ENTITIES = {
  '&mdash;': '—',
  '&ndash;': '–',
  '&deg;': '°',
  '&middot;': '·',
  '&hellip;': '…',
  '&nbsp;': ' ',
  '&eacute;': 'é',
  '&copy;': '©',
  '&euro;': '€',
  '&quot;': '"',
  '&apos;': "'",
  '&amp;': '&',
};

function read(file) {
  return execFileSync('git', ['show', `${SOURCE_REF}:${file}`], {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 8 * 1024 * 1024,
  });
}

function extractMain(html) {
  const match = html.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
  if (!match) throw new Error('no <main> found');
  return match[1];
}

/** Strip the vanilla page chrome, leaving the prose. */
function unwrap(html) {
  return (
    html
      /* The layout wrappers are the React shell's job now. */
      .replace(/<\/?section[^>]*>/gi, '')
      .replace(/<div class="container[^"]*"[^>]*>/gi, '')
      .replace(/<div class="(?:policy-content|faq-content|terms-content|about-content)[^"]*"[^>]*>/gi, '')
      .replace(/<div class="reveal"[^>]*>/gi, '')
      .replace(/<\/div>/gi, '')
      .replace(/<div[^>]*>/gi, '')
  );
}

function toJsx(html) {
  let out = html;

  /* Presentation came from css/style.css, which is deleted. The prose stylesheet
     styles by element, so class and inline-style hooks are dropped rather than
     translated into something that no longer exists. */
  out = out.replace(/\s(?:class|style|data-i18n(?:-html)?|id)="[^"]*"/gi, (match) =>
    /\sid="/i.test(match) ? match : '',
  );

  out = out.replace(/<br\s*\/?>/gi, '<br />');
  out = out.replace(/<hr\s*\/?>/gi, '<hr />');

  for (const [entity, char] of Object.entries(ENTITIES)) {
    out = out.split(entity).join(char);
  }

  const leftover = out.match(/&[a-z]+;|&#x?[0-9a-f]+;/i);
  if (leftover) throw new Error(`Unhandled entity: ${leftover[0]}`);

  /* JSX would read these as expression delimiters. */
  out = out.replace(/{/g, '&#123;').replace(/}/g, '&#125;');

  return out
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => `      ${line}`)
    .join('\n');
}

mkdirSync(OUT_DIR, { recursive: true });

for (const page of PAGES) {
  const body = toJsx(unwrap(extractMain(read(page.file))));

  const source = `/* AUTO-GENERATED by scripts/port-content.mjs — do not edit by hand.
 * Prose ported verbatim from \`${SOURCE_REF}:${page.file}\`. English only, as it was
 * there: this page carried no data-i18n attributes. Presentation classes were dropped;
 * the prose stylesheet styles by element.
 */
import styles from './prose.module.css';

export function ${page.component}() {
  return (
    <div className={styles.prose}>
${body}
    </div>
  );
}
`;

  writeFileSync(resolve(OUT_DIR, page.out), source, 'utf8');
  console.log(`  ${page.out}  ${body.split('\n').length} lines`);
}

console.log(`\nported ${PAGES.length} content pages from ${SOURCE_REF}`);
