/**
 * Port the vanilla translation dictionary into typed locale modules.
 *
 * Source of truth is `js/i18n.js` on the `web-onboarding` branch, which carries the
 * `onb_*` keys the onboarding work added in all five languages.
 *
 * **177 keys, five languages, no gaps** — measured 1 Sep 2026 by evaluating the blob the
 * way this script does. The header previously said "170 keys vs 140 — verified"; the first
 * number was wrong, and the second can no longer be re-run at all because `js/i18n.js` was
 * deleted from `main` (which is the whole reason this script reads from git, below).
 *
 * Read from git rather than the working tree, so this stays runnable after the vanilla
 * files are deleted. Nothing here is transcribed by hand; the transform is the diff.
 *
 *   node scripts/port-i18n.mjs
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'src/i18n/generated');
const SOURCE_REF = 'web-onboarding:js/i18n.js';
const LANGS = ['en', 'pl', 'de', 'el', 'sv'];

/* The dictionary stores a handful of HTML entities as literal text. The vanilla
   switcher wrote with `textContent`, so they rendered as "360&deg;" on screen —
   found and fixed on the onboarding branch for `hero_desc`, but the same class of
   bug is latent in any key that carries one. React also renders text literally,
   so every entity is decoded here, once, and what was decoded is reported. */
const ENTITIES = {
  '&deg;': '°',
  '&mdash;': '—',
  '&ndash;': '–',
  '&middot;': '·',
  '&amp;': '&',
  '&nbsp;': ' ',
  '&quot;': '"',
  '&apos;': "'",
  '&hellip;': '…',
  '&eacute;': 'é',
  '&copy;': '©',
  '&euro;': '€',
};

function readSource() {
  return execFileSync('git', ['show', SOURCE_REF], {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
  });
}

/** Evaluate the IIFE-free source against a `window` shim and hand back `CW.t`. */
function extractDictionary(source) {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(`${source}\n;globalThis.__cw_t = CW.t;`, sandbox, {
    filename: 'js/i18n.js',
    timeout: 5000,
  });
  const table = sandbox.__cw_t;
  if (!table || typeof table !== 'object') {
    throw new Error('CW.t did not evaluate to an object');
  }
  return table;
}

const decoded = [];

function decodeEntities(key, lang, value) {
  let out = value;
  for (const [entity, char] of Object.entries(ENTITIES)) {
    if (out.includes(entity)) {
      decoded.push(`${key}.${lang}: ${entity} -> ${char}`);
      out = out.split(entity).join(char);
    }
  }
  /* Numeric entities are not used today; fail loudly rather than ship "&#8212;". */
  const numeric = out.match(/&#x?[0-9a-f]+;/i);
  if (numeric) throw new Error(`Unhandled numeric entity in ${key}.${lang}: ${numeric[0]}`);
  const named = out.match(/&[a-z]+;/i);
  if (named) throw new Error(`Unhandled named entity in ${key}.${lang}: ${named[0]}`);
  return out;
}

function toLiteral(value) {
  return JSON.stringify(value);
}

function emit(lang, entries, isBase) {
  const banner = [
    '/* AUTO-GENERATED by scripts/port-i18n.mjs — do not edit by hand.',
    ` * Ported from \`${SOURCE_REF}\`. To change a string, change it there and re-run,`,
    ' * or move the key into src/i18n/strings/ if it is new to the React build.',
    ' */',
    '',
  ].join('\n');

  const body = entries
    .map(([key, value]) => `  ${key}: ${toLiteral(value)},`)
    .join('\n');

  /* English is the base: its shape defines the key union and every other locale is
     checked against it, so a stray key in a translation is a compile error rather
     than a string that silently never renders. */
  const type = isBase ? '' : ': Partial<Record<GeneratedKey, string>>';
  const imports = isBase ? '' : "import type { GeneratedKey } from './en';\n\n";
  const tail = isBase
    ? '\nexport type GeneratedKey = keyof typeof generatedEn;\n'
    : '';

  const name = `generated${lang[0].toUpperCase()}${lang.slice(1)}`;
  return `${banner}${imports}export const ${name}${type} = {\n${body}\n}${isBase ? ' as const' : ''};\n${tail}`;
}

const source = readSource();
const table = extractDictionary(source);
const keys = Object.keys(table);

mkdirSync(OUT_DIR, { recursive: true });

const missing = [];

for (const lang of LANGS) {
  const entries = [];
  for (const key of keys) {
    const row = table[key];
    const value = row?.[lang];
    if (typeof value !== 'string' || value.length === 0) {
      if (lang !== 'en') missing.push(`${key}.${lang}`);
      continue;
    }
    entries.push([key, decodeEntities(key, lang, value)]);
  }
  writeFileSync(resolve(OUT_DIR, `${lang}.ts`), emit(lang, entries, lang === 'en'), 'utf8');
  console.log(`  ${lang}.ts  ${entries.length}/${keys.length} keys`);
}

console.log(`\nported ${keys.length} keys x ${LANGS.length} languages from ${SOURCE_REF}`);
if (decoded.length) {
  console.log(`\ndecoded ${decoded.length} HTML entities:`);
  for (const line of decoded) console.log(`  ${line}`);
}
if (missing.length) {
  console.log(`\n${missing.length} translations absent in the source (will fall back to en):`);
  for (const line of missing) console.log(`  ${line}`);
}
